// GENERATED FILE - DO NOT EDIT
// ------------------------------------------------------------
// This file was generated by the FlutterFire CLI.
// ------------------------------------------------------------

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASQILpZdUy1daZkPquHn6lK0YOaACdtS0',
    appId: '1:191557000964:android:684a7bb99adc82b79b7a51',
    messagingSenderId: '191557000964',
    projectId: 'flag-pic-fdefb',
    storageBucket: 'flag-pic-fdefb.firebasestorage.app',
  );

  /// 🔹 Android

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgCr_IcCoj-WwVvdDok3s9BFncKaNaTH4',
    appId: '1:191557000964:web:d0c07df2d99282899b7a51',
    messagingSenderId: '191557000964',
    projectId: 'flag-pic-fdefb',
    authDomain: 'flag-pic-fdefb.firebaseapp.com',
    storageBucket: 'flag-pic-fdefb.firebasestorage.app',
    measurementId: 'G-36W0K562QQ',
  );

  /// 🔹 Web (ถ้าไม่ได้ใช้ Web สามารถปล่อยไว้ได้)

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA0qte0ejSnE4B8kMks2eiaiDDlNtqra4',
    appId: '1:191557000964:ios:c02779833fae9ab69b7a51',
    messagingSenderId: '191557000964',
    projectId: 'flag-pic-fdefb',
    storageBucket: 'flag-pic-fdefb.firebasestorage.app',
    iosBundleId: 'com.example.flagPic',
  );

  /// 🔹 iOS (ใส่เมื่อใช้จริง)

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA0qte0ejSnE4B8kMks2eiaiDDlNtqra4',
    appId: '1:191557000964:ios:c02779833fae9ab69b7a51',
    messagingSenderId: '191557000964',
    projectId: 'flag-pic-fdefb',
    storageBucket: 'flag-pic-fdefb.firebasestorage.app',
    iosBundleId: 'com.example.flagPic',
  );

  /// 🔹 macOS (ถ้าไม่ใช้ ปล่อยไว้)

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgCr_IcCoj-WwVvdDok3s9BFncKaNaTH4',
    appId: '1:191557000964:web:917528c790ca9b4d9b7a51',
    messagingSenderId: '191557000964',
    projectId: 'flag-pic-fdefb',
    authDomain: 'flag-pic-fdefb.firebaseapp.com',
    storageBucket: 'flag-pic-fdefb.firebasestorage.app',
    measurementId: 'G-5PBCDBR05Q',
  );

  /// 🔹 Windows (ถ้าไม่ใช้ ปล่อยไว้)
}